version: "3.9"

services:

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "auth_app"
    env_file:
      - .env
    command: sh -c "alembic upgrade head && uvicorn core.main:app --host 0.0.0.0 --port 8801"
    ports:
      - "8801:8801"
