version: "3.9"

services:
  db:
    image: postgres:16
    container_name: "users_db"
    env_file:
      - ".env"
    ports:
      - "5432:5432"

  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "alembic upgrade head && uvicorn core.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"