"""init

Revision ID: b5bf12abfbd0
Revises: b7fc570edeb6
Create Date: 2024-06-04 20:08:16.817770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5bf12abfbd0'
down_revision: Union[str, None] = 'b7fc570edeb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_password', sa.String(length=200), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('users', 'hash_password')
    # ### end Alembic commands ###
